### ISSUE TITLE
Gallery Broken 

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#19]
As mentioned before in an email, the Galleries page isn't loading, or rather its trying to load everything..

**Comment by soapdog** [comment]
The gallery tries to load everything. It was failing because the drag & drop in the map was buggy and was breaking the JSON files of the dragged pins, basically, it was saving the position correctly but it was erasing other metadata such as title and others. This caused the gallery to fail as it needs that data.

I've fixed that and now the gallery loads, but it still tries to load all items in the same page. Would a different UI be better? Maybe pagination? What do you think @JaiNatha ?

**Comment by JaiNatha** [comment]
Yes, pagination would be a good way to go

**Comment by JaiNatha** [comment]
Also, do you think we could make the images in the Gallery all uniform height and width. Obviously would require cropping, or possibly we could choose only landscape images for whatever shows up in the gallery

**Comment by soapdog** [comment]
It is better if we just select landscape images as heroes. I'm building this pagination now, it might take a while to get it right.

**Comment by soapdog** [comment]
@JaiNatha added the pagination to the galleries page.

**Comment by JaiNatha** [comment]
Is no longer loading for me. Just sits there and spins..

**Comment by soapdog** [comment]
The JSON for the Palm Corridor was broken and was causing the app to crash. There was an illegal unicode character in it.

**Comment by soapdog** [comment]
Just added a little extra check to the backend to make sure that if the json is broken, that we don't break the whole app.

@JaiNatha can you check it now? 😉 (forgot to tag you here when I solved this last week)

**Comment by JaiNatha** [comment]
yup it works
