### ISSUE TITLE
Bug - NavBar disappears on Map page

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/khm-virtual-tour#40]
On mobile only, on page load the top navBar is there, but the moment you click or drag the map, the navbar disappears.

![IMG_EA75621D3A87-3](https://user-images.githubusercontent.com/25754228/58279554-66ee9e00-7d3a-11e9-8b10-76e19d29201a.jpeg)

![IMG_EA75621D3A87-4](https://user-images.githubusercontent.com/25754228/58279561-6a822500-7d3a-11e9-8246-3ad74694e60f.jpeg)

**Comment by soapdog** [comment]
@JaiNatha, 

Can't reproduce this bug here. The UI is working on the mobile versions of Firefox, Chrome and Samsung Internet.

![ezgif com-resize](https://user-images.githubusercontent.com/23247/68311259-352f8080-00a9-11ea-91ce-b7b7c05d47b4.gif)
 
Sorry for the GIF quality, it was hard to make a GIF small enough to fit the github upload limits.

**Comment by JaiNatha** [comment]
It's working for me too. Something else must have solved it.
